app = "dark-tower"
primary_region = "ord"

[build]
  builtin = "node"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
