services:
  - type: web
    name: dark-tower
    env: node
    buildCommand: npm install
    startCommand: node run.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    ports:
      - port: 8000
        protocol: tcp
